export const HTTP_STATUS = {
  BAD_REQUEST: "BAD_REQUEST",
  UNKNOWN_ERROR: "UNKNOWN_ERROR",
  INTERNAL_SERVER_ERROR: "INTERNAL_SERVER_ERROR",
  NOT_IMPLEMENTED: "NOT_IMPLEMENTED",
  UNAUTHORIZED: "UNAUTHORIZED",
  FORBIDDEN: "FORBIDDEN",
  NOT_FOUND: "NOT_FOUND",
  METHOD_NOT_SUPPORTED: "METHOD_NOT_SUPPORTED",
  TIMEOUT: "TIMEOUT",
  CONFLICT: "CONFLICT",
  PRECONDITION_FAILED: "PRECONDITION_FAILED",
  UNSUPPORTED_MEDIA_TYPE: "UNSUPPORTED_MEDIA_TYPE",
  PAYLOAD_TOO_LARGE: "PAYLOAD_TOO_LARGE",
  UNPROCESSABLE_CONTENT: "UNPROCESSABLE_CONTENT",
  TOO_MANY_REQUESTS: "TOO_MANY_REQUESTS",
  CLIENT_CLOSED_REQUEST: "CLIENT_CLOSED_REQUEST",
} as const;

export type HttpStatusKey = keyof typeof HTTP_STATUS;
export type HttpStatusType = (typeof HTTP_STATUS)[HttpStatusKey];

export const HTTP_STATUS_CODE = {
  [HTTP_STATUS.BAD_REQUEST]: 400,
  [HTTP_STATUS.UNKNOWN_ERROR]: 500,
  [HTTP_STATUS.UNAUTHORIZED]: 401,
  [HTTP_STATUS.FORBIDDEN]: 403,
  [HTTP_STATUS.NOT_FOUND]: 404,
  [HTTP_STATUS.METHOD_NOT_SUPPORTED]: 405,
  [HTTP_STATUS.TIMEOUT]: 408,
  [HTTP_STATUS.CONFLICT]: 409,
  [HTTP_STATUS.PRECONDITION_FAILED]: 412,
  [HTTP_STATUS.PAYLOAD_TOO_LARGE]: 413,
  [HTTP_STATUS.UNSUPPORTED_MEDIA_TYPE]: 415,
  [HTTP_STATUS.UNPROCESSABLE_CONTENT]: 422,
  [HTTP_STATUS.TOO_MANY_REQUESTS]: 429,
  [HTTP_STATUS.CLIENT_CLOSED_REQUEST]: 499,
  [HTTP_STATUS.INTERNAL_SERVER_ERROR]: 500,
  [HTTP_STATUS.NOT_IMPLEMENTED]: 501,
} as const;

export type HttpStatusCodeType = (typeof HTTP_STATUS_CODE)[HttpStatusKey];
