// import "./reflect-metadata-client-side";

import { cn } from "@/shared/ui/utils";
import type { Metadata } from "next";
import { Inter as FontSans } from "next/font/google";
import { ProvidersRoot } from "./_providers/providersRoot";
import "./globals.css";
import "./module";

const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
  fallback: ["Helvetica", "Arial", "sans-serif"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={cn(
          "min-h-screen bg-background font-sans antialiased",
          fontSans.variable,
        )}
      >
        <ProvidersRoot>{children}</ProvidersRoot>
      </body>
    </html>
  );
}
