import { z } from "zod";

export const novaPoshtaSettlementBaseSchema = z.object({
  Ref: z.string().min(1), // Уникальный идентификатор
  SettlementType: z.string(),
  Latitude: z.string(),
  Longitude: z.string(),
  Description: z.string(),
  DescriptionRu: z.string(),
  DescriptionTranslit: z.string(),
  SettlementTypeDescription: z.string(),
  SettlementTypeDescriptionRu: z.string(),
  SettlementTypeDescriptionTranslit: z.string(),
  Region: z.string(),
  RegionsDescription: z.string(),
  RegionsDescriptionRu: z.string(),
  RegionsDescriptionTranslit: z.string(),
  Area: z.string(),
  AreaDescription: z.string(),
  AreaDescriptionRu: z.string(),
  AreaDescriptionTranslit: z.string(),
  Index1: z.string(),
  Index2: z.string(),
  IndexCOATSU1: z.string(),
  Delivery1: z.string(),
  Delivery2: z.string(),
  Delivery3: z.string(),
  Delivery4: z.string(),
  Delivery5: z.string(),
  Delivery6: z.string(),
  Delivery7: z.string(),
  SpecialCashCheck: z.number(), // Integer
  RadiusHomeDelivery: z.string(),
  RadiusExpressPickUp: z.string(),
  RadiusDrop: z.string(),
  Warehouse: z.string(),
});

export const novaPoshtaSettlementBaseListSchema = z.array(
  novaPoshtaSettlementBaseSchema,
);

export const novaPoshtaPostOfficeSchema = z.object({
  SiteKey: z.string(),
  Description: z.string(),
  DescriptionRu: z.string(),
  ShortAddress: z.string(),
  ShortAddressRu: z.string(),
  Phone: z.string(),
  TypeOfWarehouse: z.string(),
  Ref: z.string(),
  Number: z.string(),
  CityRef: z.string(),
  CityDescription: z.string(),
  CityDescriptionRu: z.string(),
  SettlementRef: z.string(),
  SettlementDescription: z.string(),
  SettlementAreaDescription: z.string(),
  SettlementRegionsDescription: z.string(),
  SettlementTypeDescription: z.string(),
  SettlementTypeDescriptionRu: z.string(),
  Longitude: z.string(),
  Latitude: z.string(),
  PostFinance: z.string(),
  // BicycleParking: z.string(),
  // PaymentAccess: z.string(),
  // POSTerminal: z.string(),
  // InternationalShipping: z.string(),
  // SelfServiceWorkplacesCount: z.string(),
  // TotalMaxWeightAllowed: z.string(),
  // PlaceMaxWeightAllowed: z.string(),
  // SendingLimitationsOnDimensions: z.object({
  //   Width: z.number(),
  //   Height: z.number(),
  //   Length: z.number(),
  // }),
  // ReceivingLimitationsOnDimensions: z.object({
  //   Width: z.number(),
  //   Height: z.number(),
  //   Length: z.number(),
  // }),
  // Reception: z.object({
  //   Monday: z.string(),
  //   Tuesday: z.string(),
  //   Wednesday: z.string(),
  //   Thursday: z.string(),
  //   Friday: z.string(),
  //   Saturday: z.string(),
  //   Sunday: z.string(),
  // }),
  // Delivery: z.object({
  //   Monday: z.string(),
  //   Tuesday: z.string(),
  //   Wednesday: z.string(),
  //   Thursday: z.string(),
  //   Friday: z.string(),
  //   Saturday: z.string(),
  //   Sunday: z.string(),
  // }),
  // Schedule: z.object({
  //   Monday: z.string(),
  //   Tuesday: z.string(),
  //   Wednesday: z.string(),
  //   Thursday: z.string(),
  //   Friday: z.string(),
  //   Saturday: z.string(),
  //   Sunday: z.string(),
  // }),
  // DistrictCode: z.string(),
  // WarehouseStatus: z.string(),
  // WarehouseStatusDate: z.string(),
  // WarehouseIllusha: z.string(),
  CategoryOfWarehouse: z.string(),
  // Direct: z.string(),
  // RegionCity: z.string(),
  // WarehouseForAgent: z.string(),
  // GeneratorEnabled: z.string(),
  // MaxDeclaredCost: z.string(),
  // WorkInMobileAwis: z.string(),
  // DenyToSelect: z.string(),
  // CanGetMoneyTransfer: z.string(),
  // HasMirror: z.string(),
  // HasFittingRoom: z.string(),
  // OnlyReceivingParcel: z.string(),
  // PostMachineType: z.string(),
  // PostalCodeUA: z.string(),
  // WarehouseIndex: z.string(),
  // BeaconCode: z.string(),
});

export const novaPoshtaPostOfficeListSchema = z.array(
  novaPoshtaPostOfficeSchema,
);
