import { z } from "zod";

// NOTE: Base Schema

const postOfficeBaseSchema = z.object({
  siteKey: z.string(),
  description: z.string(),
  descriptionRu: z.string(),
  shortAddress: z.string(),
  shortAddressRu: z.string(),
  phone: z.string(),
  typeOfWarehouse: z.string(),
  ref: z.string(),
  number: z.string(),
  cityRef: z.string(),
  cityDescription: z.string(),
  cityDescriptionRu: z.string(),
  settlementRef: z.string(),
  settlementDescription: z.string(),
  settlementAreaDescription: z.string(),
  settlementRegionsDescription: z.string(),
  settlementTypeDescription: z.string(),
  settlementTypeDescriptionRu: z.string(),
  longitude: z.string(),
  latitude: z.string(),
  postFinance: z.string(),
  bicycleParking: z.string(),
  paymentAccess: z.string(),
  pOSTerminal: z.string(),
  internationalShipping: z.string(),
  selfServiceWorkplacesCount: z.string(),
  totalMaxWeightAllowed: z.string(),
  placeMaxWeightAllowed: z.string(),
  sendingLimitationsOnDimensions: z.object({
    width: z.number(),
    height: z.number(),
    length: z.number(),
  }),
  receivingLimitationsOnDimensions: z.object({
    width: z.number(),
    height: z.number(),
    length: z.number(),
  }),
  reception: z.object({
    monday: z.string(),
    tuesday: z.string(),
    wednesday: z.string(),
    thursday: z.string(),
    friday: z.string(),
    saturday: z.string(),
    sunday: z.string(),
  }),
  delivery: z.object({
    monday: z.string(),
    tuesday: z.string(),
    wednesday: z.string(),
    thursday: z.string(),
    friday: z.string(),
    saturday: z.string(),
    sunday: z.string(),
  }),
  schedule: z.object({
    monday: z.string(),
    tuesday: z.string(),
    wednesday: z.string(),
    thursday: z.string(),
    friday: z.string(),
    saturday: z.string(),
    sunday: z.string(),
  }),
  districtCode: z.string(),
  warehouseStatus: z.string(),
  warehouseStatusDate: z.string(),
  warehouseIllusha: z.string(),
  categoryOfWarehouse: z.string(),
  direct: z.string(),
  regionCity: z.string(),
  warehouseForAgent: z.string(),
  generatorEnabled: z.string(),
  maxDeclaredCost: z.string(),
  workInMobileAwis: z.string(),
  denyToSelect: z.string(),
  canGetMoneyTransfer: z.string(),
  hasMirror: z.string(),
  hasFittingRoom: z.string(),
  onlyReceivingParcel: z.string(),
  postMachineType: z.string(),
  postalCodeUA: z.string(),
  warehouseIndex: z.string(),
  beaconCode: z.string(),
});

export const postOfficeShortSchema = postOfficeBaseSchema.pick({
  siteKey: true,
  description: true,
  descriptionRu: true,
  shortAddress: true,
  shortAddressRu: true,
  phone: true,
  typeOfWarehouse: true,
  ref: true,
  number: true,
  cityRef: true,
  cityDescription: true,
  cityDescriptionRu: true,
  settlementRef: true,
  settlementDescription: true,
  settlementAreaDescription: true,
  settlementRegionsDescription: true,
  settlementTypeDescription: true,
  settlementTypeDescriptionRu: true,
  longitude: true,
  latitude: true,
  postFinance: true,
});

// NOTE: Main
export const postOfficeSchema = postOfficeShortSchema;

// NOTE: UI
export const postOfficeToSelectSchema = z.object({
  value: z.string(),
  type: z.string(),
  label: z.string(),
});
